#ifndef HARDWARE_OLED_H_
#define HARDWARE_OLED_H_

#include <stdbool.h>
#include <stdint.h>

typedef struct
{
    uint32_t connectAttempts;
    uint32_t connectFailures;
    uint32_t runtimeFailures;
    uint8_t online;
} OLEDDiagnostics_t;

/*
 * Hardware configuration is generated by SysConfig:
 *
 * OLED_I2C = I2C0
 * SDA      = PA28
 * SCL      = PA31
 */
void OLED_Init(uint32_t nowMs);

/*
 * 正常车辆程序的OLED周期任务。
 *
 * 默认显示CarControl运行时间，格式为：
 *
 * HH:MM:SS
 *
 * 文本模式下调用本函数不会覆盖文本内容。
 */
void OLED_Task(uint32_t nowMs);

/*
 * OLED硬件当前是否在线。
 */
bool OLED_IsOnline(void);
void OLED_GetDiagnostics(OLEDDiagnostics_t *diagnostics);
bool OLED_ForceReconnect(uint32_t nowMs);

/*
 * 清屏并进入文本显示模式。
 */
bool OLED_ClearScreen(void);

/*
 * 在指定OLED页显示一行5x7 ASCII文本。
 *
 * line:
 *   64像素OLED：0～7
 *   32像素OLED：0～3
 *
 * 每行最多显示21个字符。
 *
 * 支持：
 *   0～9
 *   A～Z
 *   a～z（自动转换成大写）
 *   空格
 *   :
 *   -
 *   .
 *   /
 *   =
 *   %
 *   +
 *
 * 调用后自动进入文本模式。
 */
bool OLED_DrawText(uint8_t line, const char *text);

/*
 * 退出文本模式，恢复原来的HH:MM:SS计时显示。
 */
bool OLED_ResumeTimeDisplay(void);

#endif /* HARDWARE_OLED_H_ */